export const CLIENT_VERSION = ['1.0.0', '1.0.1', '1.1.0'];

const PacketType = {
  C2S_LOGIN_REQUEST: 1,
  S2C_LOGIN_RESPONSE: 2,
  S2C_GAMESYNC: 17,
  C2S_GAME_END_REQUEST: 3,
  S2C_GAME_OVER_NOTIFICATION: 4,
  C2S_SPAWN_MONSTER: 9,
  C2S_DIE_MONSTER: 10,
  S2C_ENEMY_SPAWN_MONSTER: 11,
  S2C_ENEMY_DIE_MONSTER: 12,

  // 다른 패킷 타입을 추가
};

module.exports = { PacketType };
